image: python:3.6

services:
  - postgres:9.4

variables:
  POSTGRES_DB: sodar_projectroles
  POSTGRES_USER: sodar_projectroles
  POSTGRES_PASSWORD: sodar_projectroles
  DATABASE_URL: postgres://sodar_projectroles:sodar_projectroles@postgres/sodar_projectroles

before_script:
  # SSH setup taken from https://gitlab.com/gitlab-examples/ssh-private-key
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  # Install Java 8 for sonar-scanner
  # - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections &&
  #   echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" > /etc/apt/sources.list.d/java8.list &&
  #   apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 &&
  #   apt-get update -q &&
  #   apt-get install -y oracle-java8-installer oracle-java8-set-default
  # Install sonar-scanner
  # - apt-get update -q && apt-get install -y wget unzip &&
  #     wget -O /tmp/sonar-scanner-2.8.zip https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.8.zip &&
  #     pushd /tmp &&
  #     unzip sonar-scanner-2.8.zip &&
  #     mkdir -p /opt/sonar-scanner &&
  #     mv sonar-scanner-2.8/* /opt/sonar-scanner &&
  #     chmod a+rX /opt &&
  #     chmod a+rX -R /opt/sonar-scanner &&
  #     chmod a+x /opt/sonar-scanner/bin/sonar-scanner &&
  #     popd

  - sh ./utility/install_os_gitlab.sh
  - sh ./utility/install_chrome_gitlab.sh
  - pip3 install virtualenv
  - virtualenv env
  - source env/bin/activate
  - sh ./utility/install_python_dependencies.sh

all_tests:
  script:
    - python3 manage.py collectstatic --noinput
    - coverage run --source="." manage.py test -v 2 --settings=config.settings.test
    - coverage report
  when: on_success
